-- =============================================================================
-- Pilot seed — Postpartum early recovery: confinement & rest practices
-- =============================================================================
-- The deliberately-hard slice: the topic where the four markets genuinely
-- disagree. It exercises all three evidence levels and the cross-market
-- conflict rule at once. This is illustrative pilot data for building and
-- demoing the Dashboard + Chatbot; every entry is still to pass human review.
--
-- Embeddings are NOT seeded here — they are generated by the ingestion
-- pipeline (embed on publish). This file only populates the structured spine.
--
-- Run AFTER 0001_schema.sql. Idempotent-ish: wrap in a transaction; re-running
-- requires a clean DB (fixed UUIDs would collide).
-- =============================================================================
begin;

-- --- Sources ----------------------------------------------------------------
insert into sources (id, title, publisher, url, source_type, markets, published_date, retrieved_date, credibility_tier, notes) values
('a0000000-0000-0000-0000-000000000001', 'Postpartum care clinical guidance', 'ACOG (American College of Obstetricians and Gynecologists)', 'https://www.acog.org', 'clinical_guideline', '{US}', '2018-05-01', '2026-07-31', 1, 'US clinical standard for the postpartum period.'),
('a0000000-0000-0000-0000-000000000002', 'Your body after the birth', 'NHS', 'https://www.nhs.uk', 'public_health_body', '{EU}', '2023-01-01', '2026-07-31', 1, 'UK/NHS postpartum recovery guidance.'),
('a0000000-0000-0000-0000-000000000003', 'Postpartum confinement (zuo yue zi) practices', 'TCM / national maternal health guidance (CN)', 'https://example-cn-health.gov', 'professional_org', '{CN}', '2020-01-01', '2026-07-31', 2, 'Describes mainstream confinement practice; documents the custom, not a clinical-trial endorsement.'),
('a0000000-0000-0000-0000-000000000004', 'Maternity care and postnatal guidance', 'RANZCOG', 'https://ranzcog.edu.au', 'clinical_guideline', '{AU}', '2022-01-01', '2026-07-31', 1, 'Australia/NZ clinical standard.'),
('a0000000-0000-0000-0000-000000000005', 'Community discussion: engorgement relief', 'BabyCenter Community', 'https://community.babycenter.com', 'community_forum', '{US}', null, '2026-07-31', 4, 'Lived-experience language; unverified.');

-- --- Journey stages (postpartum_early per market) ---------------------------
insert into journey_stages (id, life_stage, market, title, overview, physical, emotional) values
('b0000000-0000-0000-0000-000000000001', 'postpartum_early', 'US', 'Early Recovery (0-6 weeks) — US', 'Guided by ACOG: early mobilization, watch for warning signs, postpartum visit.', 'Early ambulation encouraged; monitor bleeding.', 'Screening for mood changes begins.'),
('b0000000-0000-0000-0000-000000000002', 'postpartum_early', 'EU', 'Early Recovery (0-6 weeks) — EU/NHS', 'Guided by NHS: gradual recovery, 6-week check.', 'Gradual return to activity; pelvic-floor guidance.', 'Health-visitor mental-health support.'),
('b0000000-0000-0000-0000-000000000003', 'postpartum_early', 'CN', 'Early Recovery (0-6 weeks) — CN (Confinement)', 'Shaped by zuo yue zi confinement tradition: extended rest, dietary and activity restrictions.', 'Extended rest; avoidance of cold exposure.', 'Family/elder support central during confinement.'),
('b0000000-0000-0000-0000-000000000004', 'postpartum_early', 'AU', 'Early Recovery (0-6 weeks) — AU', 'Guided by RANZCOG: recovery plus routine postnatal mental-health screening.', 'Recovery guidance aligned with clinical standard.', 'Routine postnatal depression screening.');

-- --- Claims -----------------------------------------------------------------
insert into claims (id, statement, life_stage, market, topic_domain, evidence_level, confidence_note, status, reviewer, review_date) values
('c0000000-0000-0000-0000-000000000001',
 'Heavy postpartum bleeding that soaks more than one pad per hour is a warning sign requiring urgent medical review.',
 'postpartum_early', 'US', 'medical_clinical', 'strong_evidence',
 'ACOG-aligned warning sign; consistent across US/AU clinical guidance.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000002',
 'Early mobilization (getting up and moving soon after an uncomplicated birth) is encouraged to support recovery.',
 'postpartum_early', 'US', 'physical', 'strong_evidence',
 'CONFLICTS with CN confinement rest (claim c...0004). Not a factual contradiction — a difference in care culture. Surface both, do not flatten.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000003',
 'The NHS advises a gradual return to activity and a postnatal check around six weeks after birth.',
 'postpartum_early', 'EU', 'physical', 'strong_evidence',
 'NHS public-health guidance.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000004',
 'In China, postpartum confinement (zuo yue zi) prescribes roughly 30 days of rest with dietary and activity restrictions.',
 'postpartum_early', 'CN', 'social_support', 'traditional_practice',
 'Mainstream everyday practice in CN, not standard US/NHS clinical advice. CONFLICTS with early-mobilization claim c...0002 by care culture.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000005',
 'Confinement custom commonly advises avoiding cold water and cold exposure (including bathing/hair-washing) during the confinement month.',
 'postpartum_early', 'CN', 'physical', 'traditional_practice',
 'Traditional practice; clinical evidence does not support the cold-avoidance rationale. Documented as custom.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000006',
 'Routine screening for postnatal depression during the early postpartum period is recommended.',
 'postpartum_early', 'AU', 'emotional_mental', 'strong_evidence',
 'RANZCOG-aligned; routine screening is standard in AU.', 'published', 'Autoploy Review', '2026-07-31'),

('c0000000-0000-0000-0000-000000000007',
 'Some mothers report that a warm compress helped relieve breast engorgement.',
 'postpartum_early', 'US', 'physical', 'anecdotal',
 'Community/lived-experience report. Unverified; captured for real-language and needs mapping.', 'published', 'Autoploy Review', '2026-07-31');

-- --- Claim <-> Source links --------------------------------------------------
insert into claim_sources (claim_id, source_id, relation) values
('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001', 'supports'),
('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000001', 'supports'),
('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', 'contradicts'), -- CN custom pulls the other way
('c0000000-0000-0000-0000-000000000003', 'a0000000-0000-0000-0000-000000000002', 'supports'),
('c0000000-0000-0000-0000-000000000004', 'a0000000-0000-0000-0000-000000000003', 'supports'),
('c0000000-0000-0000-0000-000000000005', 'a0000000-0000-0000-0000-000000000003', 'supports'),
('c0000000-0000-0000-0000-000000000006', 'a0000000-0000-0000-0000-000000000004', 'supports'),
('c0000000-0000-0000-0000-000000000007', 'a0000000-0000-0000-0000-000000000005', 'supports');

-- --- Stage <-> Claim links ---------------------------------------------------
insert into stage_claims (journey_stage_id, claim_id) values
('b0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001'),
('b0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000002'),
('b0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000007'),
('b0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000003'),
('b0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000004'),
('b0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000005'),
('b0000000-0000-0000-0000-000000000004', 'c0000000-0000-0000-0000-000000000006');

-- --- Needs -------------------------------------------------------------------
insert into needs (id, life_stage, market, need_description, existing_solutions, gap_analysis) values
('d0000000-0000-0000-0000-000000000001', 'postpartum_early', 'CN', 'Structured confinement support (meals, care, guidance) during zuo yue zi.', 'Confinement centers (yue zi zhong xin), live-in confinement nannies (yue sao), meal delivery services.', 'Highly variable quality; little integration of evidence-based clinical safety with the tradition.'),
('d0000000-0000-0000-0000-000000000002', 'postpartum_early', 'US', 'Physical recovery products and postpartum warning-sign guidance for the early weeks.', 'Postpartum recovery kits, pads, peri bottles, lactation support products.', 'Guidance is fragmented across brands and marketing; little that is genuinely evidence-rated.');

-- --- Stage <-> Need links ----------------------------------------------------
insert into stage_needs (journey_stage_id, need_id) values
('b0000000-0000-0000-0000-000000000003', 'd0000000-0000-0000-0000-000000000001'),
('b0000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000002');

-- --- Competitors -------------------------------------------------------------
insert into competitors (id, company, markets, categories, positioning, communication_notes, claims_made, evidence_check) values
('e0000000-0000-0000-0000-000000000001', 'Example Confinement Center (CN)', '{CN}', '{confinement_care,postpartum_meals,nanny_service}', 'Premium zuo yue zi confinement care.', 'Tradition-forward; family reassurance; premium wellness tone.', 'Faster recovery and better lactation via traditional confinement.', 'Recovery/lactation claims are marketing framing over a traditional-practice base; not clinically established.'),
('e0000000-0000-0000-0000-000000000002', 'Example Postpartum Recovery Brand (US)', '{US}', '{recovery_products,lactation}', 'Modern, clinical-feeling postpartum recovery kit.', 'Clean/clinical branding; empowerment tone.', 'Clinically informed recovery essentials.', 'Products are reasonable; "clinically informed" is positioning, not an evidence rating.');

-- --- Need <-> Solution (competitor) links ------------------------------------
insert into need_solutions (need_id, competitor_id) values
('d0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001'),
('d0000000-0000-0000-0000-000000000002', 'e0000000-0000-0000-0000-000000000002');

commit;
